apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Name}}-index-configmap
  namespace: {{.Namespace}}
data:
  index.html: |
    <!doctype html>
    <html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
        <style>
            html, body, #jsdos {
                width: 100%;
                height: 100%;
                margin: 0;
                padding: 0;
            }
        </style>
        <script src="js-dos.js"></script>
        <link href="js-dos.css" rel="stylesheet">
    </head>
    <body>
    <div id="jsdos"/>
    <script>
        emulators.pathPrefix = "/";
        Dos(document.getElementById("jsdos"))
            .run("{{.Bundle}}");
    </script>
    </body>
    </html>